[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arbswap = "CCR33kX4Q9iucvgN4kRga2txmtu32vxy3bXpKyxPdBQx"

[programs.devnet]
arbswap = "CCR33kX4Q9iucvgN4kRga2txmtu32vxy3bXpKyxPdBQx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["vault/program"]

[scripts]
test = "cargo test"

[hooks]
