[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arbswap = "E8ptkpV626P2neR8v4Q9UCFHoD6AMAH2aTRsEQiNDN3U"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]

[workspace]
members = ["vault/program"]
