"""P1 results generator (T1.5 + T1.6).

Calibrates the heuristic coefficients walk-forward on a synthetic price path,
freezes them, then evaluates B1/B2/B3/B4 on the held-out segment and writes
``docs/P1_RESULTS.md``. Results are reported honestly: losing regimes and the
synthetic-data limitation are stated in the output.

Run:  python -m research.sim.report
"""

from __future__ import annotations

from dataclasses import dataclass, replace

from research.reference.quote_math import QuoteParams
from research.sim.calibrate import objective, walk_forward_folds
from research.sim.engine import SimResult, simulate
from research.sim.flow import InformedFlow, NoiseFlow
from research.sim.metrics import (
    hedged_pnl,
    notional_weighted_markout,
    realized_volatility_per_sqrt_second,
    retail_half_spread_bps,
)
from research.sim.oracle import OracleModel
from research.sim.price_source import REGIME_ANNUAL_VOL, Regime, synthetic_series
from research.sim.venues import PassivePool, VaultVenue

REGIMES: tuple[Regime, ...] = ("calm", "trend", "crash")


@dataclass
class Row:
    name: str
    hedged_pnl: float
    markout_2s_bps: float
    quiet_half_spread_bps: float
    trades: int


def _price_lookup(result: SimResult):
    by_second = {i: price for i, price in enumerate(result.price_path)}
    return by_second.get


def _report(name: str, result: SimResult) -> Row:
    lookup = _price_lookup(result)
    return Row(
        name=name,
        hedged_pnl=hedged_pnl(result.value_path, result.base_path, result.price_path),
        markout_2s_bps=notional_weighted_markout(result.trades, 2, lookup),
        quiet_half_spread_bps=retail_half_spread_bps(result.trades, lookup),
        trades=len(result.trades),
    )


def _calibrate(points, *, folds: int = 2) -> QuoteParams:
    """Small walk-forward grid search; freeze the parameters chosen on train."""
    base = QuoteParams()
    folds_data = walk_forward_folds(points, folds=folds)
    chosen = base
    noise = NoiseFlow()
    informed = InformedFlow()
    for fold in folds_data:
        candidates: list[QuoteParams] = []
        for floor in (0.00005, 0.0001, 0.0002):
            for inv in (0.0002, 0.0005, 0.001):
                for vol in (0.5, 1.0, 2.0):
                    candidates.append(
                        replace(
                            base,
                            spread_floor=floor,
                            spread_min=min(base.spread_min, floor),
                            inventory_coeff=inv,
                            volatility_coeff=vol,
                        )
                    )
        scored = [
            (params, objective(params, fold.train, noise=noise, informed=informed))
            for params in candidates
        ]
        chosen = max(scored, key=lambda pair: pair[1])[0]
    return chosen


def evaluate_regime(regime: Regime, *, length: int = 2_400,
                    seed: int = 20261006) -> tuple[QuoteParams, list[Row], float]:
    prices = synthetic_series(regime=regime, length=length, seed=seed)
    folds = walk_forward_folds(prices, folds=2)
    chosen = _calibrate(prices)
    test = folds[-1].test
    sigma = realized_volatility_per_sqrt_second([p.price for p in test])

    venues = {
        "B1_passive": PassivePool(),
        "B2_fixed_spread": VaultVenue(params=chosen, engine_enabled=False),
        "B3_arbswap": VaultVenue(params=chosen),
        "B4_no_throttle": VaultVenue(params=chosen, depth_override=1.0),
    }
    rows: list[Row] = []
    for name, venue in venues.items():
        result = simulate(
            venue_name=name,
            venue=venue,
            prices=test,
            oracle=OracleModel(),
            noise=NoiseFlow(seed=seed),
            informed=InformedFlow(),
        )
        rows.append(_report(name, result))
    return chosen, rows, sigma


def render(results: dict[str, tuple[QuoteParams, list[Row], float]]) -> str:
    lines: list[str] = []
    lines.append("# P1 results: math core + simulator (T1.5, T1.6)\n")
    lines.append(
        "Generated by `python -m research.sim.report`. **Synthetic price paths** "
        "(GBM per regime, annualised vol: "
        + ", ".join(f"{r}={REGIME_ANNUAL_VOL[r]}" for r in REGIMES)
        + "). Calibration is walk-forward: parameters chosen on the earlier fold, "
        "frozen, then evaluated on the held-out later fold. These are **first "
        "results on synthetic data**; real-data replay is the next step and the "
        "numbers must not be headlined until then.\n"
    )
    for regime, (params, rows, sigma) in results.items():
        lines.append(f"## Regime: {regime} (realised sigma = {sigma:.3e} per sqrt-second)\n")
        lines.append("| Venue | Hedged PnL | Markout 2s (bps) | Quiet half-spread (bps) | Trades |")
        lines.append("|---|---|---|---|---|")
        for row in rows:
            lines.append(
                f"| {row.name} | {row.hedged_pnl:,.1f} | {row.markout_2s_bps:+.3f} | "
                f"{row.quiet_half_spread_bps:.3f} | {row.trades} |"
            )
        by_name = {row.name: row for row in rows}
        e1 = _improvement(by_name["B3_arbswap"].hedged_pnl, by_name["B1_passive"].hedged_pnl)
        lines.append("")
        lines.append(f"- **E1 (hedged PnL, B3 vs B1):** {e1:+.2%}")
        lines.append(
            f"- **E2 (2s markout):** B3 {by_name['B3_arbswap'].markout_2s_bps:+.3f} bps vs "
            f"B1 {by_name['B1_passive'].markout_2s_bps:+.3f} bps"
        )
        lines.append(
            f"- **E4 (quiet half-spread):** B3 {by_name['B3_arbswap'].quiet_half_spread_bps:.3f} bps vs "
            f"B1 {by_name['B1_passive'].quiet_half_spread_bps:.3f} bps"
        )
        lines.append(f"- Frozen params: {params}")
        lines.append("")
    lines.append("## Honest limitations\n")
    lines.append(
        "- Synthetic regimes, not real order flow; the informed/noise mix is a "
        "model, not measured.\n"
        "- Coefficients are calibrated on one fold and may overfit; sensitivity "
        "(E9) is not yet run.\n"
        "- Losing regimes are reported as-is; no result here is a product claim.\n"
    )
    return "\n".join(lines)


def _improvement(arbs: float, passive: float) -> float:
    if passive == 0:
        return 0.0
    return (arbs - passive) / abs(passive)


def main() -> None:
    results = {regime: evaluate_regime(regime) for regime in REGIMES}
    text = render(results)
    from pathlib import Path

    output = Path("docs/P1_RESULTS.md")
    output.write_text(text.rstrip() + "\n")
    print(text)
    print(f"\nwrote {output}")


if __name__ == "__main__":
    main()
